### ISSUE TITLE
Library error com.i2c.spin

### ISSUE THREAD

**Issue by jose0008** [avsa242/spin-standard-library#10]
El compilador de Propeller Tool da un error de "se esperaba un nombre único, byte, largo, palabra o instrucción de ensamblaje" en #ifdef QUIRK_SCD30. ¿Cuál sería la solución?

**Comment by avsa242** [comment]
@jose0008,
Diseñé mi bifurcación de la biblioteca estándar de giro para que se construya usando un compilador que admita un preprocesador, como FlexSpin (el desarrollador admite esto activamente) .
Desafortunadamente, el compilador oficial de Parallax, Propeller Tool (o PNut) no es compatible con un preprocesador. También _solo_ funciona en Windows, pero [FlexSpin](https://github.com/totalspectrum/spin2cpp) funciona en Windows, Mac, and Linux o otra plataforma.
Tenga en cuenta que menciono esto en spin-standard-library [README.md](https://github.com/avsa242/spin-standard-library/blob/testing/README.md).
Si tiene un requisito específico para usar la Propeller Tool, deberá modificar el código para eliminar las funciones no admitidas. Por ejemplo, ese bloque de código está destinado a hacer que el motor I2C funcione con un sensor específico (el SCD30) si se define `QUIRK_SCD30`. Si está trabajando con un dispositivo diferente, puede eliminar con seguridad todo este bloque de código:

```spin
#ifdef QUIRK_SCD30
:wrle_waitack           test    sclmask, ina            wz      ' wait: clock stretch
        if_z            jmp     #:wrle_waitack
#endif
```

Sin embargo, tenga en cuenta que si actualiza la biblioteca en cualquier momento en el futuro, esos cambios se sobrescribirán.
Recomiendo usar FlexSpin, de lo contrario, es posible que deba realizar modificaciones como esta en muchas partes de su aplicación.
