### ISSUE TITLE
Add repeated-write methods to com engines

### ISSUE THREAD

**Issue by avsa242** [avsa242/spin-standard-library#5]
Methods to repeatedly write the same byte, word, or long to the device should be added to the low-level com engines. This is useful e.g., for fast fills in a display driver, when a large display buffer can't be used.
Updated: changes will also include moving common read/write methods to a separate file, to be #included using the preprocessor. Audits of engine performance will also be included in the header of the respective objects.

- [x] com.i2c.nocog.spin
- [x] com.i2c.spin
- [x] com.parallel-8bit.spin
- [x] com.serial.nocog.spin
- [x] com.serial.spin
- [x] com.spi.4w.spin
- [x] com.spi.bitbang-nocs.spin
- [x] com.spi.bitbang.spin
- [x] com.spi.fast-nocs.spin
- [x] com.spi.fast.spin
- [x] com.spi.nocog.spin

**Comment by jose0008** [comment]
The Propeller Tool compiler gives an "expected a unique name, byte, long, word, or assembly instruction" error in #ifdef QUIRK_SCD30. What would be the solution?

**Comment by avsa242** [comment]
Completed
Serial engines updated by way of `terminal-common.spinh`

Where it wasn't appropriate, methods were left out (e.g., long support in the parallel engine, and word or long support in the serial engines).
